### PR TITLE
Central place for models

### PR DESCRIPTION
**Pull request by delasy**
The idea is to make adding new models easier to add/review.
Right now I see two PRs #36 and #30 adding two models and both of them duplicate a lot of code that makes it later harder to troubleshoot.

What I suggest instead is to have central place where contributors can add other models OR even their own models. By modifying creating model file and modifying `models/index.ts` <-- though this can be avoided by using constants, not sure what is the best way here.

In this PR:
- removed openai Convex mutation
- created `maps.playMapAction` (just a copy of `openai.playMapAction` with OpenAI stuff moved to separate file
- moved OpenAI stuff to `models/gpt-4o.ts`
- created central place for running a model: `models/index.ts`
- Added env variable `MOCK_MODELS`

### CODE REVIEW

**Comment by webdevcody** [comment]
yes, we need this.  I was thinking the same thing reading through the pull requests.

**Comment by delasy** [comment]
closes #39

**Comment by delasy** [comment]
it's ready now

**Comment by delasy** [comment]
closes #31

**Pull request merged**
